# copied from https://github.com/readthedocs/readthedocs.org/issues/8616#issuecomment-952034858

version: 2

python:
   install:
   - requirements: docs/requirements.txt

# have to explicitly enable that,
# https://docs.readthedocs.io/en/stable/config-file/v2.html#formats
formats: all
