# copied from https://github.com/readthedocs/readthedocs.org/issues/8616#issuecomment-952034858

version: 2

python:
   install:
   - requirements: docs/requirements.txt

# OMG, and this is what they do with a cross-platform language!
# from https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os
build:
    os: ubuntu-22.04
    tools:
        # outdated Sphinx used by RTD uses collections.Callable,
        # which was removed in Python 3.10
        python: "3.9"

sphinx:
    configuration: docs/source/conf.py

# have to explicitly enable that,
# https://docs.readthedocs.io/en/stable/config-file/v2.html#formats
formats: all
